alpha: 0.4
batch_size: 128
bert_config: configs/config_bert.json
clip_name: "ViT-L-14"
distill: true
embed_dim: 256
eos: '[SEP]'
image_res: 224
mlm_probability: 0.15
momentum: 0.995
optimizer: {lr1: 5e-5, lr2: 5e-06, opt: adamW, weight_decay: 0.02}
queue_size: 65536
read_local_data: false
schedular: {cooldown_epochs: 0, decay_rate: 1, epochs: 30, lr: 5e-5, min_lr: 2e-06,
  sched: cosine, warmup_epochs: 20, warmup_lr: 1e-06}
temp: 0.07
train_file: [data/mscoco_train.json, data/vgnococo.json, data/google_cc.json, data/sbu.json]
vision_width: 1024
use_checkpoint: true
