val_file: ['data/msrvtt_qa/txt/test.jsonl']
answer_list: 'data/msrvtt_qa/txt/train_ans2label.json'
label_file: ['data/msrvtt_qa/txt/test.jsonl']
videoqa_root: "video_root/msrvtt/videos/all"

read_local_data: True

bert_config: 'configs/config_bert_stride3.json'

image_res: 480
vision_width: 768
distill: True
clip_name: "ViT-B-16"
batch_size_test: 1
k_test: 128

alpha: 0.4
warm_up: True

eos: '[SEP]'

optimizer: {opt: adamW, lr1: 3e-5, lr2: 5e-6, weight_decay: 0.02}
schedular: {sched: cosine, lr: 3e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}
use_checkpoint: true